MVC Controller
wolox-training/jma-net-core pull request #2
Opened 2018-09-07 19:07 UTC by j1nma

## Summary
* I followed the MVC Controller card to learn about its behaviour and how routing is managed. The tutorial's HelloWorldController was implemented with 2 simple endpoints.

## Trello Card Link
https://trello.com/c/TDxQ5NpO/2-mvc-controllers

## Screenshots
![image](https://user-images.githubusercontent.com/19524560/45238168-5d5dfc80-b2b7-11e8-8b45-558f000d9d53.png)

![image](https://user-images.githubusercontent.com/19524560/45238225-84b4c980-b2b7-11e8-8e70-1c4133bdf064.png)

2018-09-07 20:02 UTC, j1nma commented
## Summary
* I followed the MVC Views. Changed views and layout pages. Changed the title and menu link in the layout file. Passed data from the Controller to the View.

## Trello Card Link
https://trello.com/c/knsFNSfT/3-mvc-views

## Screenshots
![image](https://user-images.githubusercontent.com/19524560/45240473-34416a00-b2bf-11e8-8ccd-959d1b0e1baf.png)

![image](https://user-images.githubusercontent.com/19524560/45240496-47ecd080-b2bf-11e8-8807-c2222963ed2b.png)

![image](https://user-images.githubusercontent.com/19524560/45240539-736fbb00-b2bf-11e8-89fd-78bc81fae53c.png)

2018-09-10 14:34 UTC, j1nma commented
## Summary
* I followed the MVC Models card. Made DB configuration as in [here](https://gist.github.com/gzamudio/424f50d7ff3f1df6c12260b851f722b3) and [here](https://gist.github.com/gzamudio/4aee3f1142d19b1eeb9ffa71442e1bb4). Generated Movie model.

## Trello Card Link
https://trello.com/c/pgML8LgN/4-mvc-models

## Screenshots
![image](https://user-images.githubusercontent.com/19524560/45303592-8b785200-b4ec-11e8-9b38-962d9a684e20.png)

2018-09-12 20:10 UTC, gzamudio requested changes

2018-09-12 20:10 UTC, gzamudio commented on src/Controllers/HelloWorldController.cs
> +        public IActionResult Welcome (string name, int numTimes = 1) {
we use brackets in next line

2018-09-12 20:10 UTC, gzamudio commented on src/Controllers/HelloWorldController.cs
>  }
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +namespace testing_net.Controllers {
by convention, we use brackets on next line, not in namespace or class or method declaration

2018-09-12 20:10 UTC, gzamudio commented on src/Controllers/MoviesController.cs
> +}
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Resources/en-US.json
> +}
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Resources/es-MX.json
> +}
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Resources/fr-FR.json
> +}
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Startup.cs
> +            services.AddDbContext<DataBaseContext>(options =>  options.UseNpgsql(Configuration["ConnectionString"]));
remove extra space before 'options.Use..'

2018-09-12 20:10 UTC, gzamudio commented on src/Startup.cs
> +
remove empty line

2018-09-12 20:10 UTC, gzamudio commented on src/Startup.cs
> +            }
check indentation

2018-09-12 20:10 UTC, gzamudio commented on src/Views/HelloWorld/Welcome.cshtml
> +</ul>
add empty line

2018-09-12 20:10 UTC, gzamudio commented on src/testing-net.csproj
> +</Project>
add an empty line

2018-09-17 12:58 UTC, j1nma commented on src/testing-net.csproj
> +</Project>
Done.

2018-09-17 12:58 UTC, j1nma commented on src/Views/HelloWorld/Welcome.cshtml
> +</ul>
Done.

2018-09-17 12:58 UTC, j1nma commented on src/Resources/en-US.json
> +}
Done.

2018-09-17 12:58 UTC, j1nma commented on src/Resources/es-MX.json
> +}
Done.

2018-09-17 12:58 UTC, j1nma commented on src/Resources/fr-FR.json
> +}
Done.

2018-09-17 13:47 UTC, gzamudio approved these changes
there are a few comments. fix the spaces and empty lines and merge. we only use empty lines at the end of files, and between methods or properties.

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/MoviesController.cs
> +            return View ();
remove the space before the parenthesis

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +            return View ();
remove the space before the parenthesis

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +            return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
remove the space before the parenthesis

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +
remove empty line

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +
remove empty line

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HomeController.cs
> +
remove empty line

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HelloWorldController.cs
> +
remove empty line

2018-09-17 13:47 UTC, gzamudio commented on src/Controllers/HelloWorldController.cs
> +            return View ();
remove the space before the parenthesis

2018-09-17 14:21 UTC, merged